name: stress_meter
description: "Stress Detection Using Generative AI And Machine Learning"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.0.0  # Firebase integration
  firebase_auth: ^5.0.0  # Firebase authentication
  cloud_firestore: ^5.0.0  # Firestore for storing user data
  provider: ^6.1.0  # State management
  google_sign_in: ^6.2.1  # Google sign-in
  image_picker: ^1.0.7  # Picking images for analysis
  speech_to_text: 7.0.0  # Voice recognition
  camera: ^0.10.5+9  # Accessing camera for face analysis
  tflite_flutter: ^0.11.0  # Running TensorFlow Lite models
  flutter_local_notifications: ^17.1.2  # Notifications for analysis results
  google_mlkit_face_detection: 0.7.0
  google_mlkit_commons: 0.4.0
  google_ml_kit: 0.15.0
  translator: ^1.0.3+1
  dart_sentiment: ^0.0.9
  google_fonts: ^6.2.1
  animate_do: ^4.0.1
  image: ^4.5.2
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  
  assets:
    - assets/images/bg1.png
    - assets/fer2013_model.tflite
    - assets/stress_model.tflite

